### ISSUE TITLE
一些角色的技能判定没有排除自己

### ISSUE THREAD

**Issue by jhwisp** [Rs794613/PcrRun#2]
https://github.com/Rs794613/PcrRun/blob/f4094f89ca9373e27278069947f7a3e3ea77b08f/__init__.py#L200

发现一个bug，在开启所有角色后，群友游玩时发现xcw使用ub时会击退自己，看代码经过测试后发现select_random(id),nselect_random(id,n)和set_kokoro_num(self,gid,kokoro_id)里的list没有删除掉自身的id导致出现这个问题。

例：select_random(id)对应的201和202行是不是应该改为
l1 = list(range(1,NUMBER+1))
l1.remove(id)

**Comment by Rs794613** [comment]
这里确实有问题，已修改，多谢建议。
